; Copyright © 2026, Polyana Fontes; Thayná Batista da Silva — Integrative Projects Observatory All rights reserved.

upload_max_filesize = 1G
post_max_size = 1G
memory_limit = 1536M
max_execution_time = 600
max_input_time = 600
